_target_: hyperbox_app.medmnist.models.darts_covid_model.DARTSModel

defaults:
    - network_cfg: da_mbv3_covid19
    - mutator_cfg: onehot_mutator
    - optimizer_cfg: adam
    - metric_cfg: accuracy
    - loss_cfg: cross_entropy
    - scheduler_cfg: null