trainer:
  _target_: pytorch_lightning.Trainer
  enable_checkpointing: true
  default_root_dir: null
  num_nodes: 1
  num_processes: 1
  gpus: 1
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  enable_progress_bar: false
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 10
  min_epochs: 1
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1
  limit_val_batches: 0.5
  limit_test_batches: 0
  limit_predict_batches: 0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 10
  accelerator: gpu
  strategy: null
  devices: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  progress_bar_refresh_rate: 0
engine:
  _target_: hyperbox_app.distributed.engine.posthoc_nbmbnet.PosthocNBMBNetEngine
  search_space_path: /home/xihe/xinhe/hyperbox_app/hyperbox_app/distributed/temp_space/nbmbnet/masks
  metric_key: 'val/acc_epoch'
  query_key: 'mean_acc'
  query_file_path: '/home/xihe/xinhe/hyperbox/hyperbox/networks/nasbench_mbnet/nasbench_mbnet_cifar10.json'
# engine:
#   _target_: hyperbox_app.distributed.engine.posthoc_nb201.PosthocNB201Engine
#   search_space_path: /home/xihe/xinhe/hyperbox_app/hyperbox_app/distributed/temp_space/nb201/masks
#   metric_key: 'val/acc_epoch'
#   query_key: 'test_acc'
model:
  network_cfg:
    _target_: hyperbox.networks.nasbench_mbnet.network.NASBenchMBNet
  # network_cfg:
  #   _target_: hyperbox.networks.nasbench201.nasbench201.NASBench201Network
  #   stem_out_channels: 16
  #   num_modules_per_stack: 5
  mutator_cfg:
    _target_: hyperbox.mutator.random_mutator.RandomMutator
  optimizer_cfg:
    _target_: torch.optim.SGD
    lr: 0.04
    weight_decay: 0.0005
    momentum: 0.9
  metric_cfg:
    _target_: torchmetrics.classification.accuracy.Accuracy
  loss_cfg:
    _target_: torch.nn.CrossEntropyLoss
  _target_: hyperbox_app.distributed.models.random_model.RandomModel
  is_net_parallel: false
datamodule:
  transforms:
    input_size:
    - 32
    - 32
    random_crop:
      enable: 1
      padding: 4
      size: 32
    random_horizontal_flip:
      enable: 1
      p: 0.5
    cutout:
      enable: 1
      n_holes: 1
      length: 16
    normalize:
      enable: 1
      mean:
      - 0.4914
      - 0.4822
      - 0.4465
      std:
      - 0.2023
      - 0.1994
      - 0.201
  _target_: hyperbox.datamodules.cifar_datamodule.CIFAR10DataModule
  data_dir: ~/datasets/cifar10
  val_split: 0.5
  num_workers: 4
  normalize: true
  batch_size: 128
  seed: 666
  shuffle: true
  pin_memory: false
  drop_last: false
  is_customized: false
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/acc
    save_top_k: 2
    save_last: true
    mode: max
    verbose: false
    dirpath: checkpoints/
    filename: '{epoch:02d}_{val/acc:.4f}'
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val/acc
    patience: 1000
    mode: max
    min_delta: 0
    check_on_train_epoch_end: false
    strict: false
logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: distributed
    name: search_nb201_gpunum1_
    save_dir: .
    offline: True
    id: null
    log_model: false
    prefix: ''
    job_type: train
    group: ''
    tags: []
seed: 9898
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
debug: false
print_config: true
ignore_warnings: true
test_after_training: true
only_test: false
pretrained_weight: null
ipdb_debug: false
