_target_: hyperbox_app.medmnist.networks.mobile3d_net.DAMobile3DNet
in_channels: 1
width_stages: [24,40,80,96,192,320]
n_cell_stages: [4,4,4,4,4,1]
stride_stages: [1,2,2,1,2,1]
width_mult: 1
num_classes: 3
dropout_rate: 0
bn_param: [0.5,1e-5]
rotate_degree: 30
crop_size: 
  - [28,28,28]
affine_degree: [10,20]
affine_scale: 
  - [0.8,1.2]
  - [1.2,1.8]
affine_shears: [10,20]
mask: null