_target_: hyperbox_app.medmnist.networks.mbnet_v4.DAMobile3DNet
in_channels: 1
width_stages: [24,40,80,96,192,320]
n_cell_stages: [4,4,4,4,4,1]
stride_stages: [2,2,2,1,2,1]
width_mult: 1
num_classes: 3
dropout_rate: 0
bn_param: [0.1,1e-3]
# search
affine_degree:
- [1.,1.,5.]
- [1.,1.,10.]
- [3.,3.,3.]
affine_scale:
- - 0.8
  - 1
- - 1.
  - 1.2
affine_shears:
- 0
brightness: [0.3,0.5]
contrast: [0.3,0.8]
blur_ks:
- [3,3]
- [2,2]
invert_val: [0.25,0.5,0.75,1]
noise_mean: 0.01
noise_std: 0.05
erase_scale:
- [0.02,0.1]
- [0.1,0.2]
erase_ratio:
- [0.3, 3.3]
ignore_keys: ['invert']
candidate_ops:
- '3x3_MBConv3'
- '3x3_MBConv4'
- '3x3_MBConv6'
- '5x5_MBConv3'
- '5x5_MBConv4'
- '7x7_MBConv3'
- '7x7_MBConv4'
- 'Identity'
mean: 0.5
std: 0.5
mask: null
