_target_: hyperbox_app.medmnist.networks.mbnet_v2.DAMobile3DNet
in_channels: 1
width_stages: [16,24,40,80,96,128,160,320]
n_cell_stages: [2,3,3,3,3,3,3,2]
stride_stages: [1,0,1,0,1,0,1,0]
width_mult: 1
first_stride: 1
num_classes: 3
dropout_rate: 0
bn_param: [0.1,1e-5]
rotate_degree: 30
# search
crop_size:
  - [28,28,28]
affine_degree: [10,30]
affine_scale:
  - [0.8,1]
  - [1.1,1.6]
affine_shears: [10,20]
mean: 0.5
std: 0.5
mask: null