_target_: hyperbox_app.medmnist.networks.da_resnet.DAResNet
in_channels: 1
num_classes: 3
rotate_degree: 30
crop_size: 
  - [28,28,28]
affine_degree: [10,20]
affine_scale: 
  - [0.8,1.2]
  - [1.2,1.8]
affine_shears: [10,20]
mask: null