_target_: hyperbox.networks.darts.darts_network.DartsNetwork
in_channels: 3
channels: 16
n_layers: 8
stem_multiplier: 3
n_nodes: 4
n_classes: 10
auxiliary: ''
# mask: /home/xihe/xinhe/hyperbox_app/hyperbox_app/darts/networks/darts/darts_mask.json
